
[yellowstone]
# The endpoint of the dragon's mouth stream.
# This is the URL where the stream can be accessed.
endpoint = "https://index.rpcpool.com"

# The x-token for the dragon's mouth stream.
# Replace <X-TOKEN> with your actual token.
x-token = "<X-TOKEN>"

# The connection timeout for the dragon's mouth stream in seconds.
# This defines how long to wait for a connection before timing out.
timeout = 60
